### PR TITLE
sitemaps and editor button

### PR DESCRIPTION
**Pull request by spyrosvl**
sitemaps for yoast
sitemaps for aioseo
editor button for bizybox creation

### CODE REVIEW

**Comment by eugenebiz** [comment]
Spyros, sorry to ask for this so late, but could you keep the projects in separate branches and pull requests? The sitemaps should be in one, and the editor button should be in another. This makes it easier for me to review the code.

**Comment by spyrosvl** [comment]
Hello Eugene. I think I have made 2 commits. The first one should have stemaps and the second sitemaps and the editor button. Do you want me to split branches for the 2 tasks?

**Comment by eugenebiz** [comment]
Hi Spyros. I actually looked at the sitemap commit itself. It contains code for the bizybox work you're doing. It's probably not worth untangling this right now, but moving forward, I would definitely appreciate separate branches for unrelated work.

**Comment by spyrosvl** [comment]
Sure Eugene. I will keep this in mind.

**Pull request merged**
