### PR TITLE
added SEO URL for single business and added checks on single business view

### PR DESCRIPTION
**Pull request by spyrosvl**

### CODE REVIEW

**Comment by eugenebiz** [comment]
Hi Spyros,

We loaded your code from your repos's master branch onto our demo site. It appears that the CSS is not being served and returns a 404 error code:

http://pubdemo.bizyhood.com/business-directory/
http://pubdemo.bizyhood.com/wp-content/plugins/bizyhood/Bizyhood/Public/css/plugin.css?ver=0.1.0

I saw some code related to serving a 404 error, though I'm not sure how it would affect the serving of the CSS. Any ideas?

**Comment by spyrosvl** [comment]
Hello Eugene,

Can you please check with your hosting company. The CSS loads fine on my staging:
http://woo.hostin.gr/wp-content/plugins/bizyhood/Bizyhood/Public/css/plugin.css?ver=0.1.0

The 404 check is for serving 404 if the id is invalid.

**Comment by scottbiz** [comment]
Spyros,

We loaded the plugin on http://pubdemo.bizyhood.com/business-directory. This is where we are seeing the issue. We can look more at it in the morning. In the meantime, if you see anything there we should try/do, let us know.

Scott

**Comment by spyrosvl** [comment]
I can see that it fails to load all css & js files in the plugin directories. What I would suggest is checking the ownership and the mode of the files (chown & chmod).

https://www.dropbox.com/s/p15fb8ns4kpdcku/Screenshot%202015-08-28%2006.39.32.png?dl=0

Also you may want to try the "old" plugin and see if this is working fine and then upload the "new" version.

**Comment by scottbiz** [comment]
This is what I found:

(1) The .zip file I created from Spyros repository has all the right files - but the top level directory in his .zip file is called bizyhood-wp-plugin-master. Whereas in our "current" plugin, the top level directory is simply called bizyhood. What I did was install Spyros plugin, then went in and changed the name of the directory under wp-content/plugins to be bizyhood. Once I did this, the Bizyhood Admin page looked correct and the top level business-directory page looks good too.

(2) However, I'm still getting 404 errors on every individual business listing. The URL looks correct, but it's not showing a valid page. I could use some help here.

I don't know what to do for #1 - I can't change the name of the directory in the zip file itself - Spyros, is there a way for you to modify the top level directory in the zip file itself so it's simply called bizyhood?

**Comment by eugenebiz** [comment]
Scott, we don't needed to change the top level directory. We take care of
that in the packaging step. We would not normally create a plugin bundle by
downloading directly from the repo. That was just for testing.

I will take a quick look at the 404 errors on pubdemo.

**Comment by scottbiz** [comment]
I'm with you Eugene - I just couldn't get the CSS to work until I did that. I don't really understand why. All the permissions were correct in the plugin - it seemed like all was setup correctly. That was the only difference.

**Comment by spyrosvl** [comment]
Hello everyone,

I made a new commit that should fix the rewrite rule issue. It seems that I can not make a new pull request until this one is closed. I am sorry, github sometimes is not that easy for me, as I am used to Bitbucket most.

About the directory url issue; Imho, Utility.php line 170 should be replace with:

    return (plugin_dir_url( __FILE__ ));

This is what the WP codex suggests too.

**Comment by eugenebiz** [comment]
Spyros, 

Please feel free to make the change in utility.php, pet your suggestion.

**Comment by spyrosvl** [comment]
I pushed the Utility.php directly to the master :)

**Comment by eugenebiz** [comment]
You should be able to work with our repo directly now, using branches for
your work.

**Comment by spyrosvl** [comment]
Thank you Eugene. I will create seperate branches per task from now on.

**Pull request merged**
